### ISSUE TITLE
SRV connectivity test does not work in e2e test after port change

### ISSUE THREAD

**Issue by lsierant** [mongodb/mongodb-kubernetes-operator#1004]
I have confirmed that this is most probably an issue with e2e tests/mongodb go driver only. I've confirmed that SRV query after port change is returning the new port correctly. Also mongosh connection to the replicaset using mongodb-srv connection string from secret is working correctly.

_Originally posted by @lsierant in https://github.com/mongodb/mongodb-kubernetes-operator/pull/995#discussion_r895612312_

**Comment by dan-mckean** [comment]
Hi, I'm Dan and I'm the Product Manager for MongoDB's support of Kubernetes.

I'm doing some work right now to try and identify how the Community Operator is being used. The Community Operator is something I inherited when I started at MongoDB, but it doesn't get as much attention from us as we'd like and we're trying to understand how it's used in order to establish its future. It will help us prioritize future issues and PRs raised by the community 🙂

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)

 If you'd rather email me instead: [dan.mckean@mongodb.com](mailto:dan.mckean@mongodb.com?subject=MongoDB%20Community%20Operator%20feedback)

Thank you in advance!
Dan
