### ISSUE TITLE
Automation config is picked up with a minute lag by agents in e2e tests.

### ISSUE THREAD

**Issue by lsierant** [mongodb/mongodb-kubernetes-operator#1010]
**What did you do to encounter the bug?**
1. Run e2e test: replica_set_mongod_port_change_with_arbiters in kind
2. Port change process progresses very slowly. 
3. After changing the port in automation config secret, there is over a minute lag when the agent discovers that the config is changed.

** What I expect? **
mongodb-agent should discover the changed config immediately.

** Logs ** 
Log in the operator: 11:42:18, immediately after this the secret is updated: 
```
2022-06-14T11:42:18.465Z	DEBUG	agent/replica_set_port_manager.go:140	Changing port in process mdb0-0 from 27017 to 40333	{"ReplicaSet": "default/mdb0"}
```
Log in the mongodb-agent container: 11:43:12.919, almost a minute later mongodb-agent still does not see changed config
```
[2022-06-14T11:43:12.919+0000] [.info] [main/components/agent.go:LoadClusterConfig:270] [11:43:12.919] clusterConfig unchanged
```

**Comment by dan-mckean** [comment]
Hi, I'm Dan and I'm the Product Manager for MongoDB's support of Kubernetes.

I'm doing some work right now to try and identify how the Community Operator is being used. The Community Operator is something I inherited when I started at MongoDB, but it doesn't get as much attention from us as we'd like and we're trying to understand how it's used in order to establish its future. It will help us prioritize future issues and PRs raised by the community 🙂

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)

 If you'd rather email me instead: [dan.mckean@mongodb.com](mailto:dan.mckean@mongodb.com?subject=MongoDB%20Community%20Operator%20feedback)

Thank you in advance!
Dan
