### ISSUE TITLE
Operator upgrade documentation

### ISSUE THREAD

**Issue by jardiacaj** [mongodb/mongodb-kubernetes-operator#1020]
In the upgrade documentation here:
https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md#upgrade-the-operator

It explains  how do deploy from pre 0.6.0 to 0.6.0 and beyond, but the upgrade path for other versions is not documented. Is this correct, or are the described steps always necessary?

What is the recommended procedure for regular upgrades? To upgrade regularly, for example from 0.7.3 to 0.7.4. Using kubectl, should the new yaml files be applied, just as explained for the installation procedure? https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md#procedure-using-kubectl

Will the upgrade cause a downtime of the databases?

Thank you for your help.

**Comment by dan-mckean** [comment]
Hi, I'm Dan and I'm the Product Manager for MongoDB's support of Kubernetes.

I'm doing some work right now to try and identify how the Community Operator is being used. The Community Operator is something I inherited when I started at MongoDB, but it doesn't get as much attention from us as we'd like and we're trying to understand how it's used in order to establish its future. It will help us prioritize future issues and PRs raised by the community 🙂

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)

 If you'd rather email me instead: [dan.mckean@mongodb.com](mailto:dan.mckean@mongodb.com?subject=MongoDB%20Community%20Operator%20feedback)

Thank you in advance!
Dan
