### ISSUE TITLE
Can only write to ReplicaSet from one Pod

### ISSUE THREAD

**Issue by realulim** [mongodb/mongodb-kubernetes-operator#1029]
I  have deployed the Operator according to the docs (version 0.7.4). This means there is a ReplicaSet of three nodes fronted by a MongoDB service.

My application runs on three different pods / nodes as well and all replicas connect to the MongoDB Service using this connection string:

`mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@my-mongo-service.mongodb-namespace.svc.cluster.local:27017`

However, only the first pod I start can write to the database. The second and third pod get this error message:

`Command failed with error 10107 (NotMaster): 'not master' on server my-mongo-service.mongodb-namespace.svc.cluster.local:27017`

So it looks like the Mongo Service sends me to a secondary node in these cases. I do know that I can specify a connection string to include all nodes and refer to the replicaset, but my application has no idea of how many MongoDB nodes are there and what they are called. What's more, through autoscaling or other means Kubernetes could at any point create new members, which my application would not know about. It needs a single point of entry and I thought that would be the Mongo Service created by the Operator.

So, is this a bug (it should actually work via the Service) or a missing feature (single point of entry feature not implemented) or a configuration error on my part?

**Comment by lsierant** [comment]
Hi @realulim,
It looks like you are not connecting to the replica set, but directly to one node which is not a primary.

Please find the `connectionString` in `my-mongo-service-connection-string` secret and generally try to connect using this guide: https://www.mongodb.com/docs/drivers/go/current/fundamentals/connection/#connect-to-a-replica-set

Let me know if it helped.

**Comment by lsierant** [comment]
@realulim 
You can use connection string from the secret or you can use directly the service. Have you tried connecting to it specifying replicaSet parameter as in linked guide? 

```mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@my-mongo-service.mongodb-namespace.svc.cluster.local:27017?replicaSet=<your replica set>
```
The service is doing simply round robin on all replicaset nodes (standard k8s service behaviour).

**Comment by lsierant** [comment]
@realulim 
Perhaps this guide is a bit misleading in this context, because it's mentioning listing all hosts in the connection string. 
The service is the entry point for the replica set. By specifying replicaSet parameter you can connect to the primary by connecting to any of the nodes. And connection to the random node is provided by the service.

**Comment by lsierant** [comment]
Sorry for the closings. It seems cmd-enter is closing, not commeting.

**Comment by realulim** [comment]
Does the operator manage those SRV records automatically with the help of Kubernetes DNS? Then this would be a good option. Otherwise it's more of an option for non-Kubernetes setups, because it's probably not a good idea to manually mess with the Kubernetes DNS.

Mounting the secret into the pod is of course no problem, but again, if the values change at runtime this won't be reflected in the environment variable. I think from the point of view of the application it should be a static string and whatever is behind that static string should be managed by the operator.

**Comment by lsierant** [comment]
> Yes, the connection string secret is managed by the operator and SRV records are in DNS, so it is always up to date.

Correction: SRV DNS entries are managed by the K8S service. The operator manages only the service. 
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#srv-records

**Comment by lsierant** [comment]
@realulim I am glad I could help.
If you think your problem is resolved, please feel free do close the ticket.

**Comment by dan-mckean** [comment]
Hi, I'm Dan and I'm the Product Manager for MongoDB's support of Kubernetes.

I'm doing some work right now to try and identify how the Community Operator is being used. The Community Operator is something I inherited when I started at MongoDB, but it doesn't get as much attention from us as we'd like and we're trying to understand how it's used in order to establish its future. It will help us prioritize future issues and PRs raised by the community 🙂

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)

 If you'd rather email me instead: [dan.mckean@mongodb.com](mailto:dan.mckean@mongodb.com?subject=MongoDB%20Community%20Operator%20feedback)

Thank you in advance!
Dan
