### ISSUE TITLE
remove `github.com/pkg/errors` as nonstandard error lib

### ISSUE THREAD

**Issue by fahedouch** [mongodb/mongodb-kubernetes-operator#1030]
[github.com/pkg/errors](https://github.com/pkg/errors) is not part of the standard library . We should move to standard library `errors` or `fmt` 

it looks like `https://github.com/pkg/errors` is used in multiple components 
```console
faheddorgaa@instance-1:~/go/src/github.com/mongoDB/mongodb-kubernetes-operator$ git grep github.com/pkg/errors  | grep -v %
cmd/versionhook/main.go:        "github.com/pkg/errors"
controllers/mongodb_tls.go:     "github.com/pkg/errors"
controllers/prometheus.go:      "github.com/pkg/errors"
controllers/replica_set_controller.go:  "github.com/pkg/errors"
controllers/replicaset_controller_test.go:      "github.com/pkg/errors"
controllers/validation/validation.go:   "github.com/pkg/errors"
go.mod: github.com/pkg/errors v0.9.1
go.sum:github.com/pkg/errors v0.8.0/go.mod h1:bwawxfHBFNV+L2hUp1rHADufV3IMtnDRdf1r5NINEl0=
go.sum:github.com/pkg/errors v0.8.1/go.mod h1:bwawxfHBFNV+L2hUp1rHADufV3IMtnDRdf1r5NINEl0=
go.sum:github.com/pkg/errors v0.9.1 h1:FEBLx1zS214owpjy7qsBeixbURkuhQAwrK5UwLGTwt4=
go.sum:github.com/pkg/errors v0.9.1/go.mod h1:bwawxfHBFNV+L2hUp1rHADufV3IMtnDRdf1r5NINEl0=
pkg/authentication/scram/scram.go:      "github.com/pkg/errors"
pkg/authentication/scramcredentials/scram_credentials.go:       "github.com/pkg/errors"
pkg/automationconfig/automation_config_builder.go:      "github.com/pkg/errors"
pkg/kube/configmap/configmap.go:        "github.com/pkg/errors"
pkg/kube/secret/secret.go:      "github.com/pkg/errors"
pkg/kube/statefulset/statefulset_builder.go:    "github.com/pkg/errors"
pkg/util/state/statemachine.go: "github.com/pkg/errors"
pkg/util/status/status_test.go: "github.com/pkg/errors"
test/e2e/setup/setup.go:        "github.com/pkg/errors"
test/e2e/util/mongotester/mongotester.go:       "github.com/pkg/errors"
test/e2e/util/wait/wait.go:     "github.com/pkg/errors"
```

I am starting a PR to clean all of this :)

**Comment by dan-mckean** [comment]
Hi, I'm Dan and I'm the Product Manager for MongoDB's support of Kubernetes.

I'm doing some work right now to try and identify how the Community Operator is being used. The Community Operator is something I inherited when I started at MongoDB, but it doesn't get as much attention from us as we'd like and we're trying to understand how it's used in order to establish its future. It will help us prioritize future issues and PRs raised by the community 🙂

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)

 If you'd rather email me instead: [dan.mckean@mongodb.com](mailto:dan.mckean@mongodb.com?subject=MongoDB%20Community%20Operator%20feedback)

Thank you in advance!
Dan

**Comment by fahedouch** [comment]
Hi @dan-mckean, thanks for pushing forward the  `mongodb-kubernetes-operator`. For me, I was in a recruitment process with mongoDB  to work on this operator I discovered that it is a good product that can make database management more cloud native so I wanted to contribute. I'm still interested in joining the mongoDB community feel free to ping me if you're looking for contributors ( here is my email fahed.dorgaa@gmail.com)
