### ISSUE TITLE
Provide support for all namespaces in the operator

### ISSUE THREAD

**Issue by eranhermush** [mongodb/mongodb-kubernetes-operator#1046]
Hi,
It seems that there is a problem with the helm chart installation of the operator.

A mongo operator cannot be created for all the namespaces and all the namespaces must be specified in the 'database.namespace' variable.

The Role/RoleBinding is used to handle this case, but we think it might be nice to have a way for ClusterRole/ClusterRoleBinding to handle all the namespaces as well.

Thank you very much!!

**Comment by mircea-cosbuc** [comment]
Hi @eranhermush ,
The operator can be configured watch all the namespaces for resources using the `operator.watchNamespace="*"` setting in your `values.yaml`. Because the operator does not know beforehand about all the namespaces you want to deploy databases in, the helm installation will not create database roles outside the namespace provided through `database.namespace` or the release namespace in case the previous value is not provided. Since we don't want an installation of the helm chart to manage service accounts in all the namespaces in the cluster, we limit the helm install to provide the database role to a single namespace. Additional roles for every namespace where the databases will be deployed can be created with:
```
helm template --namespace=<your-db-namespace>  --show-only templates/database_roles.yaml mongodb/community-operator | kubectl apply -f -
```
This behaviour is documented in the [installation docs](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md#install-in-a-different-namespace-using-kubectl), in point 4, it is mentioned that you need the `Role`, `RoleBinding` and `ServiceAccount` in the extra namespace you want your operator to watch.

**Comment by dan-mckean** [comment]
Hi, I'm Dan and I'm the Product Manager for MongoDB's support of Kubernetes.

I'm doing some work right now to try and identify how the Community Operator is being used. The Community Operator is something I inherited when I started at MongoDB, but it doesn't get as much attention from us as we'd like and we're trying to understand how it's used in order to establish its future. It will help us prioritize future issues and PRs raised by the community 🙂

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)

 If you'd rather email me instead: [dan.mckean@mongodb.com](mailto:dan.mckean@mongodb.com?subject=MongoDB%20Community%20Operator%20feedback)

Thank you in advance!
Dan
