### ISSUE TITLE
CRD in Helm package

### ISSUE THREAD

**Issue by gawsoftpl** [mongodb/mongodb-kubernetes-operator#1048]
Why in Helm chart crd is added as dependency.
This create error when I have to add this helm to other helm.
Better option will be add crd in crds directory in helm package. I can create pull request with this, but I don't know why this chart was created with this way

**Comment by slaskawi** [comment]
@irajdeep Could I kindly ask you to have a look at this?

**Comment by tzorzan** [comment]
Doing some experiments on release 0.7.4 of the Helm chart. Will be updating the issue soon.

Thx

**Comment by dan-mckean** [comment]
Hi, I'm Dan and I'm the Product Manager for MongoDB's support of Kubernetes.

I'm doing some work right now to try and identify how the Community Operator is being used. The Community Operator is something I inherited when I started at MongoDB, but it doesn't get as much attention from us as we'd like and we're trying to understand how it's used in order to establish its future. It will help us prioritize future issues and PRs raised by the community 🙂

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)

 If you'd rather email me instead: [dan.mckean@mongodb.com](mailto:dan.mckean@mongodb.com?subject=MongoDB%20Community%20Operator%20feedback)

Thank you in advance!
Dan
