### ISSUE TITLE
Is there a way to spin up a cluster but without persistence?

### ISSUE THREAD

**Issue by Loki-Afro** [mongodb/mongodb-kubernetes-operator#1056]
Is there a way to spin up a cluster but without persistence?

for our ci pipeline we don't actually need pvs since on other stages other then dev there is a mongodb as a service and creating pvs is quite time consuming and resource intensive in our cluster

if it is not clear what i mean, take a look here for the rabitmq operator you can set it like so:
simply set `storage` to 0 and one disables persistence alltogether - very convenient 

https://www.rabbitmq.com/kubernetes/operator/using-operator.html

update: i have seen someone asked that before https://github.com/mongodb/mongodb-kubernetes-operator/issues/823 but maybe things changed since then :)

**Comment by Loki-Afro** [comment]
still affecting me

**Comment by slaskawi** [comment]
@Loki-Afro Thanks for reaching out!

No, there's no option to run without persistence. The only thing you may want to try is to leverage `spec.statefulSet` (a part that enables you to override StatefulSet settings) and mount Empty Dirs in the volumes. Please bear in mind that we haven't tested this, so I can't guarantee it will work. 

Closing as running without persistence in any production systems doesn't make much sense.

**Comment by dan-mckean** [comment]
Hi, I'm Dan and I'm the Product Manager for MongoDB's support of Kubernetes.

I'm doing some work right now to try and identify how the Community Operator is being used. The Community Operator is something I inherited when I started at MongoDB, but it doesn't get as much attention from us as we'd like and we're trying to understand how it's used in order to establish its future. It will help us prioritize future issues and PRs raised by the community 🙂

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)

 If you'd rather email me instead: [dan.mckean@mongodb.com](mailto:dan.mckean@mongodb.com?subject=MongoDB%20Community%20Operator%20feedback)

Thank you in advance!
Dan
