### ISSUE TITLE
Make operator work for multi-arch clusters

### ISSUE THREAD

**Issue by laurivosandi** [mongodb/mongodb-kubernetes-operator#1070]
We have mixed arm64 and amd64 hosts in the Kubernetes cluster, to make operator reliably work in such cluster we either need to have:
* Option to add affinity rules in the [Helm chart](https://github.com/mongodb/helm-charts/blob/beb12f4d4e73da40ef3ff85bd0a3c8c452d3b183/charts/community-operator/templates/operator.yaml#L25)
* arm64 binaries for the operator

**Comment by laurivosandi** [comment]
Note that it would be preferred to have ARM64 binaries for the operator as Mongo images for ARM64 already exist

**Comment by mohsinonxrm** [comment]
@laurivosandi , may want to review https://github.com/mongodb/mongodb-kubernetes-operator/issues/299

Specifically:
https://github.com/mongodb/mongodb-kubernetes-operator/issues/299#issuecomment-1304623123

**Comment by laurivosandi** [comment]
I'm not interested in building my own images, I want to see this happening upstream.

**Comment by mohsinonxrm** [comment]
@laurivosandi , totally understand that and yes, I'd also look for official release for dev/test/ prd .

This was just me doing for learning and thought perhaps you might find helpful.

**Comment by dan-mckean** [comment]
Hi, I'm Dan and I'm the Product Manager for MongoDB's support of Kubernetes.

I'm doing some work right now to try and identify how the Community Operator is being used. The Community Operator is something I inherited when I started at MongoDB, but it doesn't get as much attention from us as we'd like and we're trying to understand how it's used in order to establish its future. It will help us prioritize future issues and PRs raised by the community 🙂

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)

 If you'd rather email me instead: [dan.mckean@mongodb.com](mailto:dan.mckean@mongodb.com?subject=MongoDB%20Community%20Operator%20feedback)

Thank you in advance!
Dan
