### ISSUE TITLE
我使用storeClass创建pvc 但是一直提示pending

### ISSUE THREAD

**Issue by anan1310** [mongodb/mongodb-kubernetes-operator#1086]
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/75241895/185564649-4846285a-d1ee-4d16-b55a-51f86d2e8b61.png">

**Comment by fengruxiao** [comment]
在spec下写 storageClassName：“你的”

**Comment by fengruxiao** [comment]
你的服务起来了吗？可以连上吗？我的pod都起来了，就是连不上

**Comment by dan-mckean** [comment]
Hi, I'm Dan and I'm the Product Manager for MongoDB's support of Kubernetes.

I'm doing some work right now to try and identify how the Community Operator is being used. The Community Operator is something I inherited when I started at MongoDB, but it doesn't get as much attention from us as we'd like and we're trying to understand how it's used in order to establish its future. It will help us prioritize future issues and PRs raised by the community 🙂

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)

 If you'd rather email me instead: [dan.mckean@mongodb.com](mailto:dan.mckean@mongodb.com?subject=MongoDB%20Community%20Operator%20feedback)

Thank you in advance!
Dan
