### ISSUE TITLE
mongodb-kubernetes-operator v0.7.6  failed to start

### ISSUE THREAD

**Issue by ramasubbaiya** [mongodb/mongodb-kubernetes-operator#1113]
**What did you do to encounter the bug?**
1. Upgrade mongo operator from 0.7.2 to 0.7.6

**What did you expect?**
Smooth upgrade to 0.7.6

**What happened instead?**
```sh
Error: failed to start container "mongodb-kubernetes-operator": Error response from daemon: OCI runtime create failed: container_linux.go:336: starting container process caused "exec: \"/usr/local/bin/entrypoint\": stat /usr/local/bin/entrypoint: no such file or directory": unknown
```

**Screenshots**

**Operator Information**
 - Operator Version: v0.7.2
 - MongoDB Image used: v4.4.0

**Kubernetes Cluster Information**
 - v1.23.7
 - Image Registry location: quay

**Comment by dan-mckean** [comment]
Hi, I'm Dan and I'm the Product Manager for MongoDB's support of Kubernetes.

I'm doing some work right now to try and identify how the Community Operator is being used. The Community Operator is something I inherited when I started at MongoDB, but it doesn't get as much attention from us as we'd like and we're trying to understand how it's used in order to establish its future. It will help us prioritize future issues and PRs raised by the community 🙂

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)

 If you'd rather email me instead: [dan.mckean@mongodb.com](mailto:dan.mckean@mongodb.com?subject=MongoDB%20Community%20Operator%20feedback)

Thank you in advance!
Dan
