### ISSUE TITLE
[Bug]  Cannot create the mongodb with config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml

### ISSUE THREAD

**Issue by oeular** [mongodb/mongodb-kubernetes-operator#1121]
when I use the config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml to create a mongodb, it is hard for me to find out where to set the specified storageclass. Could anyone give a full described mongodb-cr.yaml for me ?
 
```shell
Warning  FailedScheduling  2m26s  default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
```

**Comment by Nandha1712** [comment]
@oeular 
Are you using kubernetes cluster in AWS - Elastic Kubernetes Service?

**Comment by oeular** [comment]
@Nandha1712 Hi, I am using kubernetes cluster deployed by myself.

**Comment by Nandha1712** [comment]
Ok. May be you can check this https://youtu.be/X48VuDVv0do?t=4585

**Comment by azzarello** [comment]
> @oeular Are you using kubernetes cluster in AWS - Elastic Kubernetes Service?

Do you have any suggestions if we get the same error on EKS?

**Comment by mircea-cosbuc** [comment]
Hi @oeular, if you're using the sample CR, the operator will attempt to create `PersistentVolumeClaims` that use the default storage class configured on your cluster.
You can check for what is configured on your cluster with:
```
kubectl get storageclasses.storage.k8s.io
```
Your error is related to kubernetes not being able to bind the `PersistentVolumeClaims` created by the operator to any `PersistentVolume`. Since this is outside the scope of the operator functionality, I will close this issue, but feel free to open a new one if your run into any other issues with running a database workload with the operator.

**Comment by dan-mckean** [comment]
Hi, I'm Dan and I'm the Product Manager for MongoDB's support of Kubernetes.

I'm doing some work right now to try and identify how the Community Operator is being used. The Community Operator is something I inherited when I started at MongoDB, but it doesn't get as much attention from us as we'd like and we're trying to understand how it's used in order to establish its future. It will help us prioritize future issues and PRs raised by the community 🙂

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)

 If you'd rather email me instead: [dan.mckean@mongodb.com](mailto:dan.mckean@mongodb.com?subject=MongoDB%20Community%20Operator%20feedback)

Thank you in advance!
Dan
