### ISSUE TITLE
Can not enable TLS in both security and prometheus

### ISSUE THREAD

**Issue by sieg2010** [mongodb/mongodb-kubernetes-operator#1127]
**What did you do to encounter the bug?**
1. In CRDs, set spec.security.tls.enabled = true, and other tls settings.
2. In CRDs, set spec.prometheus.tlsSecretKeyRef a kubernetes secret name.
3. Apply CRDs.
4. There are 2 certificates mount in same mount point /var/lib/tls/server, and it cause pod can not start.

**Screenshots**
![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/19989411/191241906-e1e218ed-16dd-4b29-8885-720625a05ab5.png)

**Additional context**
Please change tlsOperatorSecretMountPath in [buildTLSPrometheus](https://github.com/mongodb/mongodb-kubernetes-operator/blob/e868003ba070f9a28a891b96355769a8616fa02c/controllers/mongodb_tls.go#L315)

**Comment by ashujain2** [comment]
I am also the same issue , tried mounting the same tls-cert within the same location but it shows the similar error. 
Any update on it ?

**Comment by ashujain2** [comment]
@mircea-cosbuc - Thanks ,waiting for get it merge into main branch .Although I have tested into my local it's working fine for now.

**Comment by dan-mckean** [comment]
Hi, I'm Dan and I'm the Product Manager for MongoDB's support of Kubernetes.

I'm doing some work right now to try and identify how the Community Operator is being used. The Community Operator is something I inherited when I started at MongoDB, but it doesn't get as much attention from us as we'd like and we're trying to understand how it's used in order to establish its future. It will help us prioritize future issues and PRs raised by the community 🙂

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)

 If you'd rather email me instead: [dan.mckean@mongodb.com](mailto:dan.mckean@mongodb.com?subject=MongoDB%20Community%20Operator%20feedback)

Thank you in advance!
Dan
