### ISSUE TITLE
Not able to assign node to mongo replica pods

### ISSUE THREAD

**Issue by DaminiBansal** [mongodb/mongodb-kubernetes-operator#1139]
**I have tried nodeAffinity/nodeSelector/podAffinity but nothing works out.**

Follows the same sample code given here but then nothing comes out, no replica got created.
https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/config/samples/mongodb.com_v1_mongodbcommunity_cr_podantiaffinity.yaml

**Same for this, even replicas didnt comeup when am passing affinities**
statefulSet:
    spec:
      selector:
        matchLabels:
          app: mongodb
      template:
        metadata:
          # label the pod which is used by the "labelSelector" in podAntiAffinty
          # you can label it witch some other labels as well -- make sure it change the podAntiAffinity labelselector accordingly
          labels:
            app: mongodb
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - nodeSelectorTerms:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - xcmongo

**Comment by mircea-cosbuc** [comment]
Hi @DaminiBansal ,
Can you share your operator installation procedure (including the version of the operator) and the full MongoDBCommunity resource you tried to deploy? Also, to debug further, you could inspect the statefulset created by the operator to determine if there are any permission errors when attempting to create the pods:
```
kubectl describe sts <your-mdb-resource-name>
```
The failure to create database pods can often be traced back to missing the application of the RBAC config in step 4: https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md#install-in-a-different-namespace-using-kubectl when the operator is configured to watch all the namespaces in the cluster.

**Comment by irajdeep** [comment]
@DaminiBansal feel free to reopen this issue if the problem still persists.

**Comment by dan-mckean** [comment]
Hi, I'm Dan and I'm the Product Manager for MongoDB's support of Kubernetes.

I'm doing some work right now to try and identify how the Community Operator is being used. The Community Operator is something I inherited when I started at MongoDB, but it doesn't get as much attention from us as we'd like and we're trying to understand how it's used in order to establish its future. It will help us prioritize future issues and PRs raised by the community 🙂

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)

 If you'd rather email me instead: [dan.mckean@mongodb.com](mailto:dan.mckean@mongodb.com?subject=MongoDB%20Community%20Operator%20feedback)

Thank you in advance!
Dan
