### ISSUE TITLE
Is there a way to connect to the outside with this operator? 

### ISSUE THREAD

**Issue by xtianus79** [mongodb/mongodb-kubernetes-operator#1140]
Is that going to be a feature?

**Comment by slaskawi** [comment]
What exactly do you mean @xtianus79 ? Would you like to connect to a Mongod, which is deployed outside of Kubernetes (e.g. in a VM)?

**Comment by xtianus79** [comment]
No mean can I get an external connection. The docs make it seem as you can't connect to the outside i.e. external access.

**Comment by slaskawi** [comment]
No, you can't do that. Please check this document for further details: https://kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address/

**Comment by kaykhan** [comment]
> 

Im a bit confused by this comment, are you suggesting its impossible to expose mongodb externally OR are you suggesting a possible solution is in the further details link?

**Comment by dan-mckean** [comment]
Hi, I'm Dan and I'm the Product Manager for MongoDB's support of Kubernetes.

I'm doing some work right now to try and identify how the Community Operator is being used. The Community Operator is something I inherited when I started at MongoDB, but it doesn't get as much attention from us as we'd like and we're trying to understand how it's used in order to establish its future. It will help us prioritize future issues and PRs raised by the community 🙂

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)

 If you'd rather email me instead: [dan.mckean@mongodb.com](mailto:dan.mckean@mongodb.com?subject=MongoDB%20Community%20Operator%20feedback)

Thank you in advance!
Dan
