### ISSUE TITLE
Link in README.md to CoreOS website does not work

### ISSUE THREAD

**Issue by craiuconstantintiberiu** [mongodb/mongodb-kubernetes-operator#1156]
**What did you do to encounter the bug?**
1. Open README.md
2. Access the link named Kubernetes Operator (pointing to https://coreos.com/operators/)
3. Site can't be reached (CoreOS website seems to be down since sometime in January 2021)

**What did you expect?**
For the link to work and access a webpage detailing what a Kubernetes operator is.

**What happened instead?**
Link does not work, accessed site can't be reached.

**Comment by dan-mckean** [comment]
Hi, I'm Dan and I'm the Product Manager for MongoDB's support of Kubernetes.

I'm doing some work right now to try and identify how the Community Operator is being used. The Community Operator is something I inherited when I started at MongoDB, but it doesn't get as much attention from us as we'd like and we're trying to understand how it's used in order to establish its future. It will help us prioritize future issues and PRs raised by the community 🙂

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)

 If you'd rather email me instead: [dan.mckean@mongodb.com](mailto:dan.mckean@mongodb.com?subject=MongoDB%20Community%20Operator%20feedback)

Thank you in advance!
Dan
