### ISSUE TITLE
I am installing MongoDBCommunity Cluster with TLS for External Access

### ISSUE THREAD

**Issue by victory4software** [mongodb/mongodb-kubernetes-operator#1163]
I have created the Certificate and the Issuer

Then I am trying to execute the below yaml file 

`
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongo-prod
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  replicaSetHorizons:
  - horizon: mongo-0.vissdatech.com:31181
  - horizon: mongo-1.vissdatech.com:31182
  - horizon: mongo-2.vissdatech.com:31183
  security:
    tls:
      enabled: true
      certificateKeySecretRef:
        name: mongodb-tls
      caConfigMapRef:
        name: ca-config-map
      optional: true
    authentication:
      modes: ["SCRAM"]
  users:
    - name: root
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: xxxxxxx
`

**What did you expect?**
I was expecting to see the pods generated 

**What happened instead?**
For get events 
![image](https://user-images.githubusercontent.com/28552955/206077924-234bfede-9d6b-4152-abfc-48f16e06747c.png)

**Screenshots**

**Operator Information**
 - 4.2.6
 - MongoDB Image used

**Kubernetes Cluster Information**
 - Minikube
 - Kubernetes version  V.1.23.3

If tried to load the existing mongodb 
![image](https://user-images.githubusercontent.com/28552955/206078246-bb54e1a5-ce13-4af6-a527-28d0a0c70b65.png)

No pods created or replicas

**Comment by victory4software** [comment]
Is there is any help for this issue

**Comment by rdxmb** [comment]
Could you please post your yaml in code-blocks? Actually it is not readable because of the random indents. 
Then I will try to have a look at this.

**Comment by dan-mckean** [comment]
Hi, I'm Dan and I'm the Product Manager for MongoDB's support of Kubernetes.

I'm doing some work right now to try and identify how the Community Operator is being used. The Community Operator is something I inherited when I started at MongoDB, but it doesn't get as much attention from us as we'd like and we're trying to understand how it's used in order to establish its future. It will help us prioritize future issues and PRs raised by the community 🙂

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)

 If you'd rather email me instead: [dan.mckean@mongodb.com](mailto:dan.mckean@mongodb.com?subject=MongoDB%20Community%20Operator%20feedback)

Thank you in advance!
Dan
