### ISSUE TITLE
Statefulset is Deploying with Default resources (CPU & RAM) and getting OOMKilled Error

### ISSUE THREAD

**Issue by sandeepg123456** [mongodb/mongodb-kubernetes-operator#1188]
When you Deploy kubernetes operator with mongodb version of 6.0.2 instead of 4.2.6 what is mentioned in this operator 0.7.6, though we pass some specific configurations for resources it is showing the default configurations after deploying.

Can we change the mongodb version to 6.0.2 with this operator version 0.7.6?

**Operator Information**
 - Operator Version  - 0.7.6
 - MongoDB Image used  - 6.0.2

![Screenshot from 2023-01-10 21-10-43](https://user-images.githubusercontent.com/107937382/211595742-a9845bb2-658e-44a4-a124-d2cd9789bf9f.png)

**Comment by slaskawi** [comment]
@sandeepg123456 Could you please post your YAML files?

**Comment by sandeepg123456** [comment]
Got the issue. I need to add versioncompatibility as well in the yaml files.
Thanks @slaskawi for your time.

**Comment by dan-mckean** [comment]
Hi, I'm Dan and I'm the Product Manager for MongoDB's support of Kubernetes.

I'm doing some work right now to try and identify how the Community Operator is being used. The Community Operator is something I inherited when I started at MongoDB, but it doesn't get as much attention from us as we'd like and we're trying to understand how it's used in order to establish its future. It will help us prioritize future issues and PRs raised by the community 🙂

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)

 If you'd rather email me instead: [dan.mckean@mongodb.com](mailto:dan.mckean@mongodb.com?subject=MongoDB%20Community%20Operator%20feedback)

Thank you in advance!
Dan
