### ISSUE TITLE
MongoDB Operator doesn't get installed as a subchart dependency in parent helm chart

### ISSUE THREAD

**Issue by MoTaher7** [mongodb/mongodb-kubernetes-operator#1192]
**What did you do to encounter the bug?**
1. Use the mongodb community operator as a sub chart

**What did you expect?**
It should get installed with the operators passed as subcharts like kafka redis etc.

**What happened instead?**
Getting error saying 
resource mapping not found for name : "mongodb-01" : namespace : "app" , no matches for kind mongodbcommunity in version mongodbcommunity.mongodb.com/v1
![image](https://user-images.githubusercontent.com/85595743/212833525-a6375055-27dc-4cad-8773-9dfc4d592744.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/85595743/212833548-adfd9943-60e9-42c4-9e0f-7fdd723c6ec6.png)

**Operator Information**
 - 0.77

**Kubernetes Cluster Information**
 - AKS 
 - 1.24
 - Internal

dependencies:
  - name: community-operator
    repository: https://mongodb.github.io/helm-charts
    version: 0.7.7

I have other operator subcharts like kafka and redis and they work flawlessly. When I install it standalone without as a subchart it works fine.

**Comment by dan-mckean** [comment]
Hi, I'm Dan and I'm the Product Manager for MongoDB's support of Kubernetes.

I'm doing some work right now to try and identify how the Community Operator is being used. The Community Operator is something I inherited when I started at MongoDB, but it doesn't get as much attention from us as we'd like and we're trying to understand how it's used in order to establish its future. It will help us prioritize future issues and PRs raised by the community 🙂

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)

 If you'd rather email me instead: [dan.mckean@mongodb.com](mailto:dan.mckean@mongodb.com?subject=MongoDB%20Community%20Operator%20feedback)

Thank you in advance!
Dan
