### ISSUE TITLE
[Discussion]: Pimary node priority and optimal Pod placement

### ISSUE THREAD

**Issue by dberardo-com** [mongodb/mongodb-kubernetes-operator#1215]
It would be great to have all ingredients to achieve the following during "steady-state" cluster operation:

* database intensive pods should be always placed on the node where the current primary is located. this way their queries will go "over localhost" and be much faster
* "high budget" machines should be more likely to become primaries during elections. If the current primary is not the "preferred one" then a new election should be triggered

Point number 2: i know about weight in replicasets, but from the doc it is not clear whether an election will be triggered if the current master is not the one with the highest weight.

The first point on the list is what i am trying to achieve, and point 2 could actually be a possible workaround. Even better would be having something like a dynamic NodeLabel being assigned by the operator on the node hosting the primary, so that this label can be used within node affinity rules by the pod.

**Comment by dan-mckean** [comment]
Hi, I'm Dan and I'm the Product Manager for MongoDB's support of Kubernetes.

I'm doing some work right now to try and identify how the Community Operator is being used. The Community Operator is something I inherited when I started at MongoDB, but it doesn't get as much attention from us as we'd like and we're trying to understand how it's used in order to establish its future. It will help us prioritize future issues and PRs raised by the community 🙂

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)

 If you'd rather email me instead: [dan.mckean@mongodb.com](mailto:dan.mckean@mongodb.com?subject=MongoDB%20Community%20Operator%20feedback)

Thank you in advance!
Dan
