### ISSUE TITLE
OLM support as in Enterprise Edition

### ISSUE THREAD

**Issue by marandalucas** [mongodb/mongodb-kubernetes-operator#1216]
What did you expect?

There are people interested in the same, but unfortunately, the previous request has been closed.
https://github.com/mongodb/mongodb-kubernetes-operator/issues/913
https://artifacthub.io/packages/olm/community-operators/mongodb-enterprise

Do you already have it in your backlog?

Congratulation on your incredible job.

**Comment by dan-mckean** [comment]
Hi @marandalucas - I've pinged you an email for us to hopefully meet and chat.

I'll update this issue here once we've had a chance to speak this over.

**Comment by marandalucas** [comment]
Hi @dan-mckean, finally we've decided to use helm instead of OLM for the moment. Thank you so much

**Comment by dan-mckean** [comment]
Hi, I'm Dan and I'm the Product Manager for MongoDB's support of Kubernetes.

I'm doing some work right now to try and identify how the Community Operator is being used. The Community Operator is something I inherited when I started at MongoDB, but it doesn't get as much attention from us as we'd like and we're trying to understand how it's used in order to establish its future. It will help us prioritize future issues and PRs raised by the community 🙂

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)

 If you'd rather email me instead: [dan.mckean@mongodb.com](mailto:dan.mckean@mongodb.com?subject=MongoDB%20Community%20Operator%20feedback)

Thank you in advance!
Dan
