### ISSUE TITLE
MongoDB Instance "Failed" Status

### ISSUE THREAD

**Issue by pseymournutanix** [mongodb/mongodb-kubernetes-operator#1250]
Hello,

I have a rather important instance setup and seems to be working fully however it looks to be in a bad state and is showing:-

```
status:
  currentMongoDBMembers: 3
  currentStatefulSetReplicas: 3
  message: 'Error deploying MongoDB ReplicaSet: error creating/updating StatefulSet:
    error creating/updating StatefulSet: StatefulSet.apps "mongodb-dre-metrics-arb"
    is invalid: spec: Forbidden: updates to statefulset spec for fields other than
    ''replicas'', ''template'', ''updateStrategy'' and ''minReadySeconds'' are forbidden'
```

Is there a way to correct this without any service disruption ?

Thanks for any help.

**Comment by dan-mckean** [comment]
Hi, I'm Dan and I'm the Product Manager for MongoDB's support of Kubernetes.

I'm doing some work right now to try and identify how the Community Operator is being used. The Community Operator is something I inherited when I started at MongoDB, but it doesn't get as much attention from us as we'd like and we're trying to understand how it's used in order to establish its future. It will help us prioritize future issues and PRs raised by the community 🙂

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)

 If you'd rather email me instead: [dan.mckean@mongodb.com](mailto:dan.mckean@mongodb.com?subject=MongoDB%20Community%20Operator%20feedback)

Thank you in advance!
Dan
