### ISSUE TITLE
How to enable TLS in okd (openshift) cluster

### ISSUE THREAD

**Issue by balait4** [mongodb/mongodb-kubernetes-operator#1305]
Hi,

I'm setting up new cluster and it is working fine without enabling the TLS. Also able to enable the TLS and working fine. I want to add users with their own certificate/key pair and restrict those to a specific DB/collection. How this can be done?

**Comment by dan-mckean** [comment]
We currently only support creating users via the Operator with SCRAM authentication: https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/users.md

I'm doing some work right now to try and identify how the Community Operator is being used. I'm the Product Manager for MongoDB's support of Kubernetes. The Community Operator is something I inherited when I started but it doesn't get as much attention from us as we'd like, and we're trying to understand how it's used in order to establish it's future. It will help us prioritise things like this 🙂 

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)
