### ISSUE TITLE
Steps to upgrade from 4.4 to 6.0 via 5.0?

### ISSUE THREAD

**Issue by prachiwaghulkar** [mongodb/mongodb-kubernetes-operator#1478]
**What did you do to encounter the bug?**
Upgraded from 4.4 to 5.0.23. The MongoDBCommunity operator went into running state. When I tried to go to 6.0.12 I encountered the following error in the logs

```
{"t":{"$date":"2024-01-25T07:57:26.086+00:00"},"s":"F",  "c":"CONTROL",  "id":20573,   "ctx":"initandlisten","msg":"Wrong mongod version","attr":{"error":"UPGRADE PROBLEM: Found an invalid featureCompatibilityVersion document (ERROR: Location4926900: Invalid featureCompatibilityVersion document in admin.system.version: { _id: \"featureCompatibilityVersion\", version: \"4.4\" }. See https://docs.mongodb.com/master/release-notes/5.0-compatibility/#feature-compatibility. :: caused by :: Invalid feature compatibility version value, expected '5.0' or '5.3' or '6.0. See https://docs.mongodb.com/master/release-notes/5.0-compatibility/#feature-compatibility.). If the current featureCompatibilityVersion is below 5.0, see the documentation on upgrading at https://docs.mongodb.com/master/release-notes/5.0/#upgrade-procedures."}}
{"t":{"$date":"2024-01-25T07:57:26.086+00:00"},"s":"I",  "c":"REPL",     "id":4784900, "ctx":"initandlisten","msg":"Stepping down the ReplicationCoordinator for shutdown","attr":{"waitTimeMillis":15000}}
{"t":{"$date":"2024-01-25T07:57:26.086+00:00"},"s":"I",  "c":"REPL",     "id":4794602, "ctx":"initandlisten","msg":"Attempting to enter quiesce mode"}

```
Even I tried to update the feature compatibility after upgrade to 5.0.23 using command 
`db.adminCommand( { setFeatureCompatibilityVersion: "5.0" } )` 
However the feature compatibility version remained the same. Refer log file below and the commands executed.

[log.txt](https://github.com/mongodb/mongodb-kubernetes-operator/files/14051242/log.txt)

<img width="731" alt="image" src="https://github.com/mongodb/mongodb-kubernetes-operator/assets/59005441/3e5bae62-d9f7-4033-9717-266f7d3d8c03">

**What did you expect?**
After 4.4 to 5.0 upgrade, The set FeatureCompatibilityVersion command should have set the value to 5.0.

**What happened instead?**
he set FeatureCompatibilityVersion command didn't set the value to 5.0 and remained 4.4

**Operator Information**
 - Operator Version: mongodb/mongodb-kubernetes-operator : 0.8.3
 - MongoDB Image used: 5.0.23

**Comment by Pavanipogula** [comment]
Hey

Even i am facing the same issue while trying to upgrade the mongo from 4.4 to 6.0 via 5.0

`{"t":{"$date":"2024-01-29T09:21:46.835+00:00"},"s":"F",  "c":"CONTROL",  "id":20573,   "ctx":"initandlisten","msg":"Wrong mongod version","attr":{"error":"UPGRADE PROBLEM: Found an invalid featureCompatibilityVersion document (ERROR: Location4926900: Invalid featureCompatibilityVersion document in admin.system.version: { _id: \"featureCompatibilityVersion\", version: \"4.4\" }. See https://docs.mongodb.com/master/release-notes/5.0-compatibility/#feature-compatibility. :: caused by :: Invalid feature compatibility version value, expected '5.0' or '5.3' or '6.0. See https://docs.mongodb.com/master/release-notes/5.0-compatibility/#feature-compatibility.). If the current featureCompatibilityVersion is below 5.0, see the documentation on upgrading at https://docs.mongodb.com/master/release-notes/5.0/#upgrade-procedures."}}`

**Operator Information**:

-  Community operator version : 0.9.0
- MongoDB image used : 5.0.24

**Comment by mbeckDWRE** [comment]
Hi,
same issue here as well when trying to upgrade from 4.4.10 to 5.0.24 (and eventually 6.0.13):

Some seconds after the `setFeatureCompatibilityVersion: "5.0"` command, getParameters returns 5.0, but then it is 4.4 again.

From the attached log, I see the following parameter changes:

`{"t":{"$date":"2024-02-01T09:50:17.768+00:00"},"s":"I",  "c":"REPL",     "id":20459,   "ctx":"conn22163","msg":"Setting featureCompatibilityVersion","attr":{"currentVersion":"4.4","newVersion":"upgrading from 4.4 to 5.0"}}
{"t":{"$date":"2024-02-01T09:50:19.785+00:00"},"s":"I",  "c":"REPL",     "id":20459,   "ctx":"conn22163","msg":"Setting featureCompatibilityVersion","attr":{"currentVersion":"upgrading from 4.4 to 5.0","newVersion":"5.0"}}
{"t":{"$date":"2024-02-01T09:50:23.276+00:00"},"s":"I",  "c":"REPL",     "id":20459,   "ctx":"conn10","msg":"Setting featureCompatibilityVersion","attr":{"currentVersion":"5.0","newVersion":"downgrading from 5.0 to 4.4"}}
{"t":{"$date":"2024-02-01T09:50:25.291+00:00"},"s":"I",  "c":"REPL",     "id":20459,   "ctx":"conn10","msg":"Setting featureCompatibilityVersion","attr":{"currentVersion":"downgrading from 5.0 to 4.4","newVersion":"4.4"}}
`

But no real indication why it is going back to 4.4 again.



[MongoUpgrade.txt](https://github.com/mongodb/mongodb-kubernetes-operator/files/14123462/MongoUpgrade.txt)



**Operator Information:**

Community operator version : 0.8.3
MongoDB image used : 5.0.24

**Comment by Pavanipogula** [comment]
Hi,
The upgrade of mongo is done successfully after explicitly setting the variable `featureCompatibilityVersion` in mongodb spec to 5.0 while upgrading db from 5.0 series to 6.0 series.
`apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
spec:
  featureCompatibilityVersion: "6.0"
  members: 3
  .......
  `

**Comment by trevor-carlson1** [comment]
Hi, 
I am still getting the log `"Wrong mongod version","attr":{"error":"UPGRADE PROBLEM: Found an invalid featureCompatibilityVersion document (ERROR: Location4926900: Invalid featureCompatibilityVersion document in admin.system.version: { _id: \"featureCompatibilityVersion\", version: \"4.4\" }. See https://docs.mongodb.com/master/release-notes/5.0-compatibility/#feature-compatibility. :: caused by :: Invalid feature compatibility version value, expected '5.0' or '5.3' or '6.0. See https://docs.mongodb.com/master/release-notes/5.0-compatibility/#feature-compatibility.). If the current featureCompatibilityVersion is below 5.0, see the documentation on upgrading at https://docs.mongodb.com/master/release-notes/5.0/#upgrade-procedures."}}`
even after setting `featureCompatibilityVersion: "5.0"` when upgrading from  5.0.26 to 6.0.14. Anybody else run into this/

**Comment by Pavanipogula** [comment]
@trevor-carlson1 It looks like the featureCompatibility is not updated properly. You can check the featureCompatibiltyVersion  in the database by using this command `db.adminCommand( { getParameter: 1, featureCompatibilityVersion: 1 } )` in admin database and set it to the desired vale using `db.adminCommand( { setFeatureCompatibilityVersion: "5.0" } )`

**Comment by slaskawi** [comment]
The answer from @Pavanipogula is correct here: https://github.com/mongodb/mongodb-kubernetes-operator/issues/1478#issuecomment-1945452389

The Operator relies on the Automation Config for setting proper FCV. You can find more information in:

* https://www.mongodb.com/docs/ops-manager/current/reference/cluster-configuration/
* https://www.mongodb.com/docs/manual/reference/command/setFeatureCompatibilityVersion/

I'm closing this issue as explained. If you feel there's something we could do here to help you, please reopen it.
