### ISSUE TITLE
MongoDB Failed Status

### ISSUE THREAD

**Issue by pseymournutanix** [mongodb/mongodb-kubernetes-operator#1552]
Got an issue where we ran out of space and it caused pods to crash.

Added some space to the mdb resource and the pods recovered but now I am getting a `Failed` status for this instance.

```
Status:
  Current Mongo DB Members:       3
  Current Stateful Set Replicas:  3
  Message:                        Error deploying MongoDB ReplicaSet: error creating/updating StatefulSet: error creating/updating StatefulSet: StatefulSet.apps "mongodb-dre" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy' and 'minReadySeconds' are forbidden
```

There is nothing to show me exactly what the requested updates are.

Is there anyway to reconcile this without downtime, or recreating the statefulset it's a heavily used MDB instance.

Operator: 0.7.6
MongoDB: 6.0.2

Many thanks.

**Comment by jadesoturi** [comment]
we are facing a similar issue on 2 of our mongo-db instances created with the operator. The CRD reports status failed, but the stateful set and the mongodb instances are actually running. However, pushing any changes fail with the same error message. Deleting and recreating the statefulset is a no-go due to this being in production.

**Comment by KarooolisZi** [comment]
@nammn May you please have a look at this comment?
https://github.com/mongodb/mongodb-kubernetes-operator/issues/1613#issuecomment-2333758420
