### ISSUE TITLE
Readme operator installation process is broken

### ISSUE THREAD

**Issue by user12344321** [mongodb/mongodb-kubernetes-operator#172]
Following the installation procedure from the readme shows an error and does not create the `example-mongodb` pod. Looking into the logs of the `crd/mongodb.mongodb.com` shows: 
> error: no kind "CustomResourceDefinition" is registered for version "apiextensions.k8s.io/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"

After doing a git bisect, it seems this has been broken since `82f4dc9 2020-08-25 | CLOUDP-66799: Configure SCRAM users`

**Comment by bznein** [comment]
Hi @user12344321 The documentation has been heavily updated with the new features (related to SCRAM users) since you posted. Can you please try by following the new one and let us know if everything works fine? 

Thanks

**Comment by luisamador** [comment]
I've also come across an installation issue while following the installation steps.

![image](https://user-images.githubusercontent.com/18208396/95983958-c0210b00-0e22-11eb-9ee7-fed18511f3a4.png)

the file "deploy/crds/mongodb.com_mongodb_scram_crd.yaml" doesn't exist anymore. I ran this command instead in order to create the CRD:

```kubectl create -f deploy/crds/mongodb.com_mongodb_crd.yaml```

**Comment by irajdeep** [comment]
The documentation has been updated this issue was created. 
The current document points to the right path for CRDs
