### ISSUE TITLE
Shard cluster support

### ISSUE THREAD

**Issue by tuapuikia** [mongodb/mongodb-kubernetes-operator#231]
Is it possible to deploy mongodb shared cluster using community operator?

**Comment by bznein** [comment]
Hi @tuapuikia,

at the moment the Community Operator doesn't support sharded cluster.

**Comment by maxisam** [comment]
Any chance it will be supported in the future?

**Comment by jamesbroadhead** [comment]
@maxisam Thanks for your interest! 

It's possible - but isn't scheduled in the next 3-6 months. 
We would accept a series of pull-requests to add support if you're able to contribute. 

We keep an eye on feature requests on feedback.mongodb.com -  if you file a request there, and it accumulates votes, that will feed into our planning.

**Comment by raman-nbg** [comment]
Is there already a feature request on feedback.mongodb.com? Couldn't find any but I'm not sure...

**Comment by supersaeyan** [comment]
> @maxisam Thanks for your interest!
> 
> It's possible - but isn't scheduled in the next 3-6 months.
> We would accept a series of pull-requests to add support if you're able to contribute.
> 
> We keep an eye on feature requests on feedback.mongodb.com - if you file a request there, and it accumulates votes, that will feed into our planning.

Hi @jamesbroadhead 
I would be interested to take that up.
Could you help me get started as i am new to kubernetes development and open source as well.
Any reading material or other helpful resources that can help me understand what is expected from the first PR, would be great.

**Comment by roshanr10** [comment]
^ I would also be interested in contributing to this effort

**Comment by misiek08** [comment]
There is no sense developing this feature here again. It's [already supported in Enterprise version](https://www.mongodb.com/docs/kubernetes-operator/master/tutorial/deploy-sharded-cluster/#deploy-sharded-cluster). Will this be ever open sourced, or we need to fork and work on this as OSS rebels? 😄

**Comment by jamesbroadhead** [comment]
The design of the Enterprise and Community Operators is quite different - they share some code, but not the code which deploys MongoDB instances (the Enterprise Operator relies on Ops or Cloud Manager). 

As a result, sharded cluster support in this Operator will need to be new code - whether it's written by a community member or the MongoDB Kubernetes team. 

We would accept Community PRs to add Sharding support, as long as they had the right amount of testing so that we could  support the feature. No forking needed - that's what OSS is all about.
