### ISSUE TITLE
Access the MongoDB from outside the cluster for development operations.

### ISSUE THREAD

**Issue by GioPat** [mongodb/mongodb-kubernetes-operator#267]
Hello,
I was able to test my deployment by:
- Spawning an ubuntu container in the k8s cluster
- Installing mongo shell
- Using the connection string that is in the documentation: 
`mongo "mongodb://<service-object-name>.<my-namespace>.svc.cluster.local:27017/?replicaSet=<replica-set-name>" --username <username> --password <password> --authenticationDatabase <authentication-database>`

After these steps I was able to connect _intra cluster_

I'm struggling though to connect to the MongoDB from outside the cluster for testing environment.
I tried to port-forward the service with the following command:
`kubectl port-forward svc/my-mongo-db 27017:27017`

But when I try to connect using MongoDB Compass I get this error:
![image](https://user-images.githubusercontent.com/9217515/102322965-2a1f7300-3f80-11eb-839c-e9700a0fb16a.png)

My advise is to add a procedure in the documentation to test the MongoDB when installed both intra or inter cluster.

Can you enlight me on the topic?

Thank you in advance.

Update
---
I tried to simply connect using the mongo cli from my PC and it's working without issues using this simple command:
`mongo`

So I guess the issue is on the MongoDB Compass side

**Comment by rajavignesh** [comment]
@GioPat

Are you able to connect to ReplicaSet from outside the Kubernetes cluster? 
I tried NodePort and the connection success rate is not consistent.

**Comment by GioPat** [comment]
> @GioPat
> 
> Are you able to connect to ReplicaSet from outside the Kubernetes cluster?
> I tried NodePort and the connection success rate is not consistent.

@rajavignesh I am able to connect from outside by port-fowarding the service and using the Mongo Shell.
With MongoDB compass I'm not able to connect.
If you write your connection string format I can try with that.

**Comment by Azaron76** [comment]
I face the same problem.
I try to connect with MongoDB Compass to my newly created MongoDB ReplicaSet and it fails.
I used NodePort for service first and then tried NodePort expose for all pods like described in the documentation.

But it's not working. Is this a problem of Compass or a configuration problem from the ReplicaSet generated by Kubernetes Community Operator?

**Comment by SrinivasMajeti** [comment]
@GioPat 

I work with Raj and here is what I am seeing (the connection is changing to pod hostname and trying to access it from outside)

[mongodb@~]$ mongo --host ea-mongodb/lxrke-dbdev-worker2:31217 -u xxxxxxx -p xxxxxx
MongoDB shell version v4.0.19
connecting to: mongodb://lxrke-dbdev-worker2:31217/?gssapiServiceName=mongodb&replicaSet=ea-mongodb
2021-01-19T16:20:00.689-0500 I NETWORK  [js] Starting new replica set monitor for ea-mongodb/lxrke-dbdev-worker2:31217
2021-01-19T16:20:00.759-0500 I NETWORK  [js] Successfully connected to lxrke-dbdev-worker2:31217 (1 connections now open to lxrke-dbdev-worker2:31217 with a 5 second timeout)
2021-01-19T16:20:00.793-0500 I NETWORK  [js] **changing hosts to ea-mongodb/ea-mongodb-0.ea-mongodb-svc.mongodb-ns.svc.cluster.local:27017,ea-mongodb-1.ea-mongodb-svc.mongodb-ns.svc.cluster.local:27017,ea-mongodb-2.ea-mongodb-svc.mongodb-ns.svc.cluster.local:27017 from ea-mongodb/lxrke-dbdev-worker2:31217**
2021-01-19T16:20:01.316-0500 W NETWORK  [js] Unable to reach primary for set ea-mongodb
2021-01-19T16:20:01.316-0500 I NETWORK  [js] Cannot reach any nodes for set ea-mongodb. Please check network connectivity and the status of the set. This has happened for 1 checks in a row.
2021-01-19T16:20:01.825-0500 W NETWORK  [js] Unable to reach primary for set ea-mongodb
2021-01-19T16:20:01.825-0500 I NETWORK  [js] Cannot reach any nodes for set ea-mongodb. Please check network connectivity and the status of the set. This has happened for 2 checks in a row.
2021-01-19T16:20:02.334-0500 W NETWORK  [js] Unable to reach primary for set ea-mongodb
2021-01-19T16:20:02.334-0500 I NETWORK  [js] Cannot reach any nodes for set ea-mongodb. Please check network connectivity and the status of the set. This has happened for 3 checks in a row.
2021-01-19T16:20:02.843-0500 W NETWORK  [js] Unable to reach primary for set ea-mongodb

**Comment by dgdevops** [comment]
I am facing the same issue while trying to access the Replica Set using kubectl port-forward. I created a kubernetes service for all the 3 replicas (P-S-S) and did a local port forward but got the following error: `getaddrinfo ENOTFOUND mongodb.mongodb-qa-svc.mongodb.svc.cluster.local`. Due to this domain name resolution error the Replica Set cannot be access from either outside of the kubernetes cluster or from any other cluster in the same region. Does anyone have a workaround or a working solution for this issue?

**Comment by suhavan-gupta** [comment]
I was able to access the MongoDB cluster running on Kubernetes using mongodb-kubernetes-operator(community) using the following commands

`kubectl port-forward svc/my-mongo-db 27018:27017`

` mongo --port 27018 --username XXXX --password XXXX`

This technique always connects me to the first pod(which sometimes acts as a secondary node in the MongoDB cluster). I think svc should be intelligent enough to connect me to the primary node instead of the first pod. Am I missing something here?

Is there any way I can access the cluster without port forwarding?

**Comment by suhavangupta** [comment]
To access the MongoDB from inside the Kubernetes cluster, use the following commands -

`mongo "mongodb://<service-object-name>.<my-namespace>.svc.cluster.local:27017/?replicaSet=<replica-set-name>" --username <username> --password <password> --authenticationDatabase <authentication-database>`

To access MongoDB from outside the Kubernetes cluster, you will have to create a Network Load Balancer (if your cloud provider is AWS) or equivalent service in your cloud provider. Ensure that your LB allows TCP protocol and points to the same pods as the service resource created by `mongodb-kubernetes-operator`.

If you want to create a quick and temporary connection to MongoDB from outside the cluster, use the port forwarding feature of Kubernetes.

`kubectl port-forward svc/my-mongo-db 27018:27017`

`mongo --port 27018 --username XXXX --password XXXX`

This is not a bug but expected behaviour. However, more documentation will be appreciated.

**Comment by ramy-ahmed** [comment]
In the Advanced Connection Options, in the General section, I have checked the "Direct Connection" option and it works for me.

**Comment by jishnuraj-chimera** [comment]
The Advanced Connection Options -> General section no longer has "Direction Connection" checkbox.
Anyone still facing the same issue?

**Comment by MartinLoeper** [comment]
Could someone explain please why direct connection works here and why e.g. server selection with replica set  does not?
