### ISSUE TITLE
One line of log output Running ./manager then container quits

### ISSUE THREAD

**Issue by jmjava** [mongodb/mongodb-kubernetes-operator#385]
I am following the instructions for bringing up the operator and its quitting without any logs

I get one line of output in the pod: Running ./manager

the events show this: there does not seem to be any clue to the cause

Normal Pulled 11m (x4 over 12m) Successfully pulled image
Normal Created 11m (x4 over 12m) Created container mongodb-kubernetes-operator
Normal Started 11m (x4 over 12m) Started container mongodb-kubernetes-operator
Normal Pulling 10m (x5 over 12m) Pulling image “quay.io/mongodb/mongodb-kubernetes-operator:0.5.1”
Warning BackOff 2m18s (x48 over 12m) Back-off restarting failed container

**Comment by rodrigovalin** [comment]
Hello @jmjava 

How did you install the operator? Have you followed the instructions from [here](../blob/master/docs/install-upgrade.md#procedure)? If you have followed the instructions from the docs, can you tell me the output of this command?

    kubectl -n <namespace-where-operator-is-installed> get deployment/mongodb-kubernetes-operator -o yaml

The problem could be caused by a missing environment variable `WATCH_NAMESPACE`.

**Comment by jmjava** [comment]
@rodrigovalin thanks for your input that fixed it!   It was improper editing in the manager.yaml that produced the issue
