### ISSUE TITLE
Is this operator considered production ready??

### ISSUE THREAD

**Issue by steeling** [mongodb/mongodb-kubernetes-operator#415]
Running into a few issues:

deleting a MongoDBCommunity resource doesn't clean up all the things, serviceName not provisioned, applying some updates gets accepted yet results in a no-op. I've been playing with this for this than less 2 hours and ran into those issues already. 

Can you clarify, maybe highlight some of the known bugs, or put a warning that this is currently in development? Please advise

**Comment by theburi** [comment]
Hi
The current state of this project is Beta. v 0.5.2
We are working on stability and adding more features. 

We intentionally don't clean up some resources to keep data persist.
It would be great if you could log issues that you find. It helps us to identify new use cases.

**Comment by javierguzman** [comment]
So in future this will be official (from mongo people) way to roll out a mongoDB replica set on Kubernetes? I am asking because I have seen stuff from other people like mongo-k8s-sidecar project or mongodb-replicaset helm chart.

I am building a web application and right now I am using only one pod of MongoDB, I would like to have a replica set so I can use "transaction sessions". So even though this project is still in beta, I would like to know if the intent is to become the way to go for deployment in future rather than relying on HELM or other's people projects.

Thank you in advance and regards
