### ISSUE TITLE
Error on upgrading operator to 0.7.2

### ISSUE THREAD

**Issue by dragonknight88** [mongodb/mongodb-kubernetes-operator#884]
**What did you do to encounter the bug?**
1. Upgrade the operator to 0.7.2
2. Apply updated crd 

**What did you expect?**

Upgrade gets applied successfully

**What happened instead?**

> CustomResourceDefinition.apiextensions.k8s.io "mongodbcommunity.mongodbcommunity.mongodb.com" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema

**Operator Information**
 - Operator Version : 0.7.2
 - MongoDB Image used : 4.4.0

**Kubernetes Cluster Information**
 - Version 1.21
 - Image Registry location quay

**Additional context**

Had to remove default `ignoreUnknownUsers` from manager.yaml to get it working.

**Comment by dragonknight88** [comment]
Was upgrading from 0.6.2.

**Comment by mircea-cosbuc** [comment]
In this case, your issue seems to be related to https://github.com/mongodb/mongodb-kubernetes-operator/issues/621 and https://github.com/mongodb/mongodb-kubernetes-operator/issues/631. Can you try adding 
```
preserveUnknownFields: false
```
to the `spec` in the CRD yaml, or an even cleaner approach as documented here: https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md#upgrade-the-operator . With newer versions, the CRD version moved to
```
apiVersion: apiextensions.k8s.io/v1
```
and cleanly upgrading it requires deleting and re-creating it.
