### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pierreozoux** [mongodb/mongodb-kubernetes-operator#97]
Hi,

and thanks for working on this.

I find it confusing to have the repo with the apache license and the agent with a proprietary license. Especially when you can't run this repo without the agent.

I'd kindly recommend you to change the approach to make it clearer for everybody and avoid confusion. (When people are confused, or they didn't expect something, sometimes they become angry and it is frustrating for both parties, I'd like to avoid this, that's why I try to give you my little advice).

Either you relicense the agent to be apache as well, in this case, everything is clearly open source. This would be my preferred option :)

Or you relicense this repo with the same license as the agent. Hence making it clear that you can't use this repo without any proprietary software (which is confusing right now because it is apache).

Hope you understand my wish :)

Currently, I'd qualify this repo as fopensource, it looks like open source and it isn't, and it creates frustration to people that arrive to this conclusion after some digging.

IMHO, you'd gain to clearly label it as proprietary or open source, either way, but clearly.

Thanks for spending time reading me and best wishes :)

**Comment by jamesbroadhead** [comment]
Hi Pierre -

Thanks for your thoughts on this. 

The licensing situation for the code in this repo is a little nuanced, and I had hoped that the segment in our [README](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/README.md#license) explained it. 

We discussed this approach quite a lot internally, and there are many pros and cons to the various approaches that you suggested.

The license shown by Github on the repo is auto-detected, and we cannot change it directly. This is explained in their [Learn more about repository licenses](https://help.github.com/articles/licensing-a-repository/#disclaimer) link. I will make a PR to try to make this more clear. 

It is worth noting that the source code of the Operator is fully available under an Apache license - we wanted to make the code available so that others could benefit from it and extend it. For this reason, the entire repo isn’t covered by the “Free for Commercial Use” license. 

The Agent represents 7 years of work to automate deployments of MongoDB in a reliable and predictable manner. Previously, it was only available to Enterprise customers. We see releasing it under the “Free for Commercial Use” license as a contribution to help Community users of MongoDB.

In the early stages of this project, we discussed releasing the Agent under other licenses. The Agent codebase is large, and contains elements which we want to remain proprietary. As a result, moving to make it open-source or source-available would require both splitting the codebase and building a module system for it to load the proprietary components. This would be both costly and would have delayed our timeline to release the Community Operator. Ultimately, we decided on this approach for now. 

We use feedback.mongodb.com for feature requests - if you file a ticket for Open-Sourcing the Agent, and it accumulates votes, it will help us make the case internally to continue to discuss licensing changes for the Agent. 

All the best 

James
